apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ml-pipeline-ui-proxy-tls
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  ports:
    - name: http-oauth
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
