apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  application-crd-id: kubeflow-pipelines
resources:
- ../base
- apiserver
- common
- ui
- persistence-agent
- scheduled-workflow
patchesStrategicMerge:
  - apiserver/patches/api-server-patch.yaml
  - apiserver/patches/service-ml-pipeline_patch.yaml
  - apiserver/patches/sa_patch.yaml
  - ui/patches/ui-deployment_patch.yaml
  - ui/patches/ui-service_patch.yaml
  - ui/patches/ui-sa_patch.yaml
  - scheduled-workflow/deployment-patch.yaml
  - persistence-agent/deployment-patch.yaml