kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ml-pipeline-ui-oauth
  annotations:
    kubernetes.io/tls-acme: "true"
  namespace: kubeflow
spec:
  to:
    kind: Service
    name: ml-pipeline-ui
  port:
    targetPort: http-oauth
  tls:
    termination: Reencrypt