apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  template:
    spec:
      volumes:
        - name: proxy-tls
          secret:
            secretName: ml-pipeline-ui-proxy-tls
      containers:
        - name: ml-pipeline-ui
          env:
            - name: ENABLE_AUTHZ
              value: 'true'
            - name: KUBEFLOW_USERID_HEADER
              value: X-Forwarded-User
            - name: KUBEFLOW_USERID_PREFIX
            - name: ML_PIPELINE_SERVICE_HOST
              value: ml-pipeline
            - name: ML_PIPELINE_SERVICE_PORT
              value: '8888'
            - name: DISABLE_GKE_METADATA
              value: 'true'
#            - name: DEPLOYMENT
#              value: MARKETPLACE
        - name: oauth-proxy
          args:
            - --https-address=:8443
            - --provider=openshift
            - --openshift-service-account=ml-pipeline-ui
            - --upstream=http://localhost:3000
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
            - '--openshift-delegate-urls={"/": {"k8sresource": "services", "verb": "get", "name": "ml-pipeline-ui"}}'
            - --skip-auth-regex='(^/metrics|^/apis/v1beta1/healthz)'
            - --pass-user-headers=true # Header: X-Forwarded-User
          image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.10
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              path: /oauth/healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /oauth/healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-tls
