apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list