apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - env:
            - name: V2_DRIVER_IMAGE
              value: ghcr.io/kubeflow/kfp-driver:sha-83791e7
            - name: V2_LAUNCHER_IMAGE
              value: ghcr.io/kubeflow/kfp-launcher:sha-83791e7
          name: ml-pipeline-api-server
      serviceAccountName: ml-pipeline
