apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - env:
            - name: V2_DRIVER_IMAGE
              value: gcr.io/ml-pipeline/kfp-driver:latest
            - name: V2_LAUNCHER_IMAGE
              value: gcr.io/ml-pipeline/kfp-launcher:latest
          name: ml-pipeline-api-server
      serviceAccountName: ml-pipeline
