apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  application-crd-id: kubeflow-pipelines
namespace: kubeflow
resources:
- route.yaml
- namespace.yaml

patchesStrategicMerge:
- api-server-patch.yaml
- deploy-patch.yaml
- cache-deploy-patch.yaml