apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  application-crd-id: kubeflow-pipelines
namespace: kubeflow
resources:
- route.yaml
- namespace.yaml
- scc.yaml
- https://github.com/kubeflow/pipelines//manifests/kustomize/base/installs/generic?ref=master
- https://github.com/kubeflow/pipelines//manifests/kustomize/base/pipeline/cluster-scoped?ref=master
- https://github.com/kubeflow/pipelines//manifests/kustomize/base/metadata/base?ref=master
- https://github.com/kubeflow/pipelines//manifests/kustomize/third-party/argo/installs/cluster?ref=master
- https://github.com/kubeflow/pipelines//manifests/kustomize/third-party/minio/base?ref=master
- https://github.com/kubeflow/pipelines//manifests/kustomize/third-party/mysql/base?ref=master

patchesStrategicMerge:
- api-server-patch.yaml
- deploy-patch.yaml
- cache-deploy-patch.yaml
- ui-patch.yaml

images:
- name: gcr.io/ml-pipeline/api-server
  newName: quay.io/hukhan/ds-pipelines-api-server
  newTag: fix_deps_1
- name: gcr.io/ml-pipeline/frontend
  newName: quay.io/hukhan/ds-pipelines-frontend
  newTag: fix_deps_1
- name: gcr.io/ml-pipeline/persistenceagent
  newName: quay.io/hukhan/persistenceagent
  newTag: fix_deps_1
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: quay.io/hukhan/ds-pipelines-scheduledworkflow
  newTag: fix_deps_1
- name: gcr.io/ml-pipeline/workflow-controller
  newName: quay.io/argoproj/workflow-controller
  newTag: v3.4.16
