apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-runs
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - runs
      - experiments
      - jobs
    verbs:
      - get
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list